[package]
name = "rust-localserver"
version = "0.1.0"
edition = "2021"

[dependencies]
mio = { version = "1.0", features = ["net", "os-poll"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
log = "0.4"
env_logger = "0.11"
thiserror = "1.0"